CREATE TABLE IF NOT EXISTS contas (
    numero INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agencia INTEGER NOT NULL DEFAULT 1,
    tipo INTEGER NOT NULL,
    titular VARCHAR(150) NOT NULL,
    saldo NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    limite NUMERIC(12, 2),
    aniversario INTEGER,
    data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_contas_agencia_positiva
        CHECK (agencia > 0),

    CONSTRAINT ck_contas_tipo_valido
        CHECK (tipo IN (1, 2)),

    CONSTRAINT ck_contas_titular_obrigatorio
        CHECK (btrim(titular) <> ''),

    CONSTRAINT ck_contas_saldo_nao_negativo
        CHECK (saldo >= 0),

    CONSTRAINT ck_contas_dados_por_tipo
        CHECK (
            (
                tipo = 1
                AND limite IS NOT NULL
                AND limite >= 0
                AND aniversario IS NULL
            )
            OR
            (
                tipo = 2
                AND limite IS NULL
                AND aniversario BETWEEN 1 AND 31
            )
        )
);
